version: "2.2"
services:
  jobmanager:
    image: flink:1.14
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager 
    networks: 
      - beamflink
    

  taskmanager:
    image: flink:1.14
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks: 
      - beamflink
    
     

  pythonsdk:
    image: apache/beam_python3.9_sdk
    depends_on:
      - taskmanager
    command: --worker_pool
    scale: 1
    ports:
      - "50000:50000"
    expose:
      - 50000
    networks: 
      - beamflink

    



networks:
  beamflink:
    driver: host
